<?php

require_once __DIR__ . '/config.php';
require_once __DIR__ . '/request.php';

/**
 * Rebecca panel adapter.
 *
 * Rebecca requires every user to belong to one service. A service can expose
 * every protocol configured on its hosts, so the bot stores one service id as
 * the panel/product protocol selection and returns every link generated by it.
 */

function rebeccaNormalizeUrl($url)
{
    $url = trim((string) $url);
    $url = preg_replace('#/(dashboard|api)/?$#i', '', rtrim($url, '/'));
    return rtrim((string) $url, '/');
}

function rebeccaPanel($panelOrName)
{
    if (is_array($panelOrName)) {
        return $panelOrName;
    }
    return select('marzban_panel', '*', 'name_panel', $panelOrName, 'select');
}

function rebeccaErrorMessage($response, $decoded = null)
{
    if (!empty($response['error'])) {
        return (string) $response['error'];
    }
    if (!is_array($decoded)) {
        $decoded = json_decode((string) ($response['body'] ?? ''), true);
    }
    if (is_array($decoded)) {
        foreach (['detail', 'message', 'error', 'msg'] as $key) {
            if (!array_key_exists($key, $decoded) || $decoded[$key] === '') {
                continue;
            }
            return is_scalar($decoded[$key])
                ? (string) $decoded[$key]
                : json_encode($decoded[$key], JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
        }
    }
    $status = (int) ($response['status'] ?? 0);
    return $status > 0 ? 'Rebecca API error (' . $status . ')' : 'Connection to Rebecca failed';
}

function rebeccaTokenPanel($panelOrCode, $verify = true)
{
    $panel = is_array($panelOrCode)
        ? $panelOrCode
        : select('marzban_panel', '*', 'code_panel', $panelOrCode, 'select');
    if (!$panel || !is_array($panel)) {
        return ['ok' => false, 'msg' => 'پنل ربکا پیدا نشد.'];
    }

    if ($verify && !empty($panel['datelogin'])) {
        $cached = json_decode($panel['datelogin'], true);
        $cachedAt = isset($cached['time']) ? strtotime($cached['time']) : false;
        if (!empty($cached['access_token']) && $cachedAt && (time() - $cachedAt) < 2700) {
            return ['ok' => true, 'access_token' => $cached['access_token']];
        }
    }

    $url = rebeccaNormalizeUrl($panel['url_panel'] ?? '') . '/api/admin/token';
    $request = new CurlRequest($url);
    $request->setHeaders([
        'Accept: application/json',
        'Content-Type: application/x-www-form-urlencoded',
    ]);
    $response = $request->post([
        'username' => (string) ($panel['username_panel'] ?? ''),
        'password' => (string) ($panel['password_panel'] ?? ''),
    ]);
    $body = json_decode((string) ($response['body'] ?? ''), true);
    if ((int) ($response['status'] ?? 0) < 200 || (int) ($response['status'] ?? 0) >= 300 || empty($body['access_token'])) {
        return [
            'ok' => false,
            'status' => (int) ($response['status'] ?? 0),
            'msg' => rebeccaErrorMessage($response, $body),
        ];
    }

    $cache = json_encode([
        'time' => date('Y-m-d H:i:s'),
        'access_token' => $body['access_token'],
    ], JSON_UNESCAPED_SLASHES);
    if (!empty($panel['code_panel'])) {
        update('marzban_panel', 'datelogin', $cache, 'code_panel', $panel['code_panel']);
    }
    return ['ok' => true, 'access_token' => $body['access_token']];
}

function rebeccaRequest($panelOrName, $method, $path, $payload = null, $retry = true)
{
    $panel = rebeccaPanel($panelOrName);
    if (!$panel || !is_array($panel)) {
        return ['ok' => false, 'status' => 0, 'msg' => 'پنل ربکا پیدا نشد.', 'data' => []];
    }
    $token = rebeccaTokenPanel($panel, $retry);
    if (!$token['ok']) {
        return ['ok' => false, 'status' => $token['status'] ?? 0, 'msg' => $token['msg'], 'data' => []];
    }

    $request = new CurlRequest(rebeccaNormalizeUrl($panel['url_panel']) . '/' . ltrim($path, '/'));
    $request->setHeaders(['Accept: application/json', 'Content-Type: application/json']);
    $request->setBearerToken($token['access_token']);
    $method = strtolower((string) $method);
    if ($method === 'get') {
        $response = $request->get();
    } elseif ($method === 'post') {
        $response = $request->post($payload === null ? '{}' : json_encode($payload, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES));
    } elseif ($method === 'put') {
        $response = $request->put($payload === null ? '{}' : json_encode($payload, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES));
    } elseif ($method === 'delete') {
        $response = $request->delete($payload === null ? null : json_encode($payload, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES));
    } else {
        return ['ok' => false, 'status' => 0, 'msg' => 'Unsupported Rebecca request method', 'data' => []];
    }

    $status = (int) ($response['status'] ?? 0);
    $body = json_decode((string) ($response['body'] ?? ''), true);
    if ($status === 401 && $retry) {
        if (!empty($panel['code_panel'])) {
            update('marzban_panel', 'datelogin', null, 'code_panel', $panel['code_panel']);
        }
        return rebeccaRequest($panel, $method, $path, $payload, false);
    }
    if ($status < 200 || $status >= 300) {
        return ['ok' => false, 'status' => $status, 'msg' => rebeccaErrorMessage($response, $body), 'data' => $body ?: []];
    }
    return ['ok' => true, 'status' => $status, 'msg' => '', 'data' => is_array($body) ? $body : []];
}

function rebeccaCheckConnection($panelOrName)
{
    return rebeccaRequest($panelOrName, 'get', '/api/system');
}

function rebeccaUsersSummary($panelOrName)
{
    $all = rebeccaRequest($panelOrName, 'get', '/api/users?offset=0&limit=1');
    if (!$all['ok']) {
        return $all;
    }
    $active = rebeccaRequest($panelOrName, 'get', '/api/users?offset=0&limit=1&status=active');
    return [
        'ok' => true,
        'status' => $all['status'],
        'msg' => '',
        'total' => (int) ($all['data']['total'] ?? 0),
        'active' => $active['ok'] ? (int) ($active['data']['total'] ?? 0) : null,
    ];
}

function rebeccaListUsers($panelOrName, $status = '', $offset = 0, $limit = 1000)
{
    $query = http_build_query([
        'offset' => max(0, (int) $offset),
        'limit' => max(1, min(1000, (int) $limit)),
        'status' => trim((string) $status),
    ]);
    $response = rebeccaRequest($panelOrName, 'get', '/api/users?' . $query);
    if (!$response['ok']) {
        return $response + ['items' => [], 'total' => 0];
    }
    return [
        'ok' => true,
        'status' => $response['status'],
        'msg' => '',
        'items' => is_array($response['data']['users'] ?? null) ? $response['data']['users'] : [],
        'total' => (int) ($response['data']['total'] ?? 0),
    ];
}

function rebeccaGetServices($panelOrName)
{
    $response = rebeccaRequest($panelOrName, 'get', '/api/v2/services?offset=0&limit=1000');
    if (!$response['ok']) {
        return $response + ['items' => []];
    }
    $items = $response['data']['services'] ?? $response['data']['items'] ?? $response['data'];
    $items = is_array($items) ? array_values(array_filter($items, function ($item) {
        return is_array($item) && (int) ($item['id'] ?? 0) > 0;
    })) : [];
    return ['ok' => true, 'status' => $response['status'], 'msg' => '', 'items' => $items];
}

function rebeccaGetService($panelOrName, $serviceId)
{
    return rebeccaRequest($panelOrName, 'get', '/api/v2/services/' . (int) $serviceId);
}

function rebeccaNormalizeServiceId($value)
{
    if (is_string($value)) {
        $decoded = json_decode($value, true);
        if (json_last_error() === JSON_ERROR_NONE) {
            $value = $decoded;
        }
    }
    if (is_array($value)) {
        if (isset($value['service_id'])) {
            return max(0, (int) $value['service_id']);
        }
        $value = reset($value);
    }
    return max(0, (int) $value);
}

function rebeccaResolveServiceId($panel, $product = null)
{
    if (is_array($product)) {
        $serviceId = rebeccaNormalizeServiceId($product['inbounds'] ?? null);
        if ($serviceId > 0) {
            return $serviceId;
        }
    }
    foreach (['proxies', 'inbounds', 'inboundid'] as $field) {
        $serviceId = rebeccaNormalizeServiceId($panel[$field] ?? null);
        if ($serviceId > 0) {
            return $serviceId;
        }
    }
    return 0;
}

function rebeccaAbsoluteUrl($panel, $url)
{
    $url = trim((string) $url);
    if ($url === '') {
        return '';
    }
    if (preg_match('#^https?://#i', $url)) {
        return $url;
    }
    return rebeccaNormalizeUrl($panel['url_panel'] ?? '') . '/' . ltrim($url, '/');
}

function rebeccaSafeFileName($name, $fallback = 'rebecca-config')
{
    $name = rawurldecode(basename(trim((string) $name)));
    $name = preg_replace('/[^A-Za-z0-9._-]+/', '-', $name);
    $name = trim((string) $name, '.-_');
    if ($name === '') {
        $name = $fallback;
    }
    return substr($name, 0, 100);
}

function rebeccaProfileInfo($content, $fileName = '', $contentType = '')
{
    $content = ltrim((string) $content, "\xEF\xBB\xBF\r\n\t ");
    if ($content === '') {
        return null;
    }
    if (preg_match('/^\s*\[Interface\]\s*$/mi', $content) && preg_match('/^\s*\[Peer\]\s*$/mi', $content)) {
        return [
            'extension' => 'conf',
            'mime' => 'application/x-wireguard-profile',
            'caption' => 'فایل WireGuard سرویس شما',
        ];
    }
    if (preg_match('/^\s*(client|tls-client)\s*$/mi', $content)
        && preg_match('/(^\s*(remote|dev)\s+)|(<ca>|<cert>|<key>)/mi', $content)) {
        return [
            'extension' => 'ovpn',
            'mime' => 'application/x-openvpn-profile',
            'caption' => 'فایل OpenVPN سرویس شما',
        ];
    }

    $extension = strtolower((string) pathinfo($fileName, PATHINFO_EXTENSION));
    if ($extension === 'zip' && substr($content, 0, 2) === 'PK') {
        return [
            'extension' => 'zip',
            'mime' => 'application/zip',
            'caption' => 'فایل اتصال سرویس شما',
        ];
    }
    if ($extension === 'mobileconfig' && stripos($content, '<plist') !== false) {
        return [
            'extension' => 'mobileconfig',
            'mime' => trim((string) $contentType) ?: 'application/x-apple-aspen-config',
            'caption' => 'فایل اتصال سرویس شما',
        ];
    }
    $genericMimeTypes = [
        'p12' => 'application/x-pkcs12',
        'pfx' => 'application/x-pkcs12',
        'crt' => 'application/x-x509-ca-cert',
        'cer' => 'application/pkix-cert',
        'pem' => 'application/x-pem-file',
        'key' => 'application/octet-stream',
    ];
    if (isset($genericMimeTypes[$extension]) && stripos($content, '<html') === false) {
        return [
            'extension' => $extension,
            'mime' => $genericMimeTypes[$extension],
            'caption' => 'فایل اتصال سرویس شما',
        ];
    }
    if ($extension === 'xml' && stripos($content, '<html') === false && preg_match('/<\?xml|<[^>]+>/', $content)) {
        return [
            'extension' => 'xml',
            'mime' => 'application/xml',
            'caption' => 'فایل اتصال سرویس شما',
        ];
    }
    return null;
}

function rebeccaResolveResourceUrl($baseUrl, $resourceUrl)
{
    $resourceUrl = html_entity_decode(trim((string) $resourceUrl), ENT_QUOTES | ENT_HTML5, 'UTF-8');
    if ($resourceUrl === '' || preg_match('#^(data|javascript):#i', $resourceUrl)) {
        return '';
    }
    if (preg_match('#^https?://#i', $resourceUrl)) {
        return $resourceUrl;
    }
    $base = parse_url((string) $baseUrl);
    if (!$base || empty($base['host'])) {
        return '';
    }
    $origin = ($base['scheme'] ?? 'https') . '://' . $base['host'];
    if (!empty($base['port'])) {
        $origin .= ':' . $base['port'];
    }
    if (strpos($resourceUrl, '//') === 0) {
        return ($base['scheme'] ?? 'https') . ':' . $resourceUrl;
    }
    if ($resourceUrl[0] === '/') {
        return $origin . $resourceUrl;
    }
    $path = isset($base['path']) ? dirname($base['path']) : '';
    return $origin . rtrim(str_replace('\\', '/', $path), '/') . '/' . ltrim($resourceUrl, '/');
}

function rebeccaDownloadResource($url, array $allowedHosts = [], $maxBytes = 8388608, $userAgent = 'MirzaBot-Rebecca/1.0')
{
    $url = trim((string) $url);
    $parts = parse_url($url);
    $host = strtolower((string) ($parts['host'] ?? ''));
    if (!in_array(strtolower((string) ($parts['scheme'] ?? '')), ['http', 'https'], true) || $host === '') {
        return ['ok' => false, 'msg' => 'Invalid profile URL'];
    }
    $allowedHosts = array_values(array_unique(array_filter(array_map('strtolower', $allowedHosts))));
    if ($allowedHosts && !in_array($host, $allowedHosts, true)) {
        return ['ok' => false, 'msg' => 'Profile host is not allowed'];
    }

    $body = '';
    $headers = [];
    $tooLarge = false;
    $ch = curl_init($url);
    curl_setopt_array($ch, [
        CURLOPT_RETURNTRANSFER => false,
        CURLOPT_FOLLOWLOCATION => true,
        CURLOPT_MAXREDIRS => 3,
        CURLOPT_CONNECTTIMEOUT => 6,
        CURLOPT_TIMEOUT => 15,
        CURLOPT_SSL_VERIFYPEER => false,
        CURLOPT_SSL_VERIFYHOST => false,
        CURLOPT_ENCODING => '',
        CURLOPT_USERAGENT => (string) $userAgent,
        CURLOPT_HTTPHEADER => ['Accept: application/json,text/plain,text/html,application/octet-stream,*/*'],
        CURLOPT_HEADERFUNCTION => function ($curl, $header) use (&$headers) {
            $length = strlen($header);
            $parts = explode(':', $header, 2);
            if (count($parts) === 2) {
                $headers[strtolower(trim($parts[0]))] = trim($parts[1]);
            }
            return $length;
        },
        CURLOPT_WRITEFUNCTION => function ($curl, $chunk) use (&$body, &$tooLarge, $maxBytes) {
            if (strlen($body) + strlen($chunk) > $maxBytes) {
                $tooLarge = true;
                return 0;
            }
            $body .= $chunk;
            return strlen($chunk);
        },
    ]);
    $executed = curl_exec($ch);
    $status = (int) curl_getinfo($ch, CURLINFO_HTTP_CODE);
    $finalUrl = (string) curl_getinfo($ch, CURLINFO_EFFECTIVE_URL);
    $error = curl_error($ch);
    curl_close($ch);
    if ($executed === false || $tooLarge || $status < 200 || $status >= 300) {
        return ['ok' => false, 'status' => $status, 'msg' => $tooLarge ? 'Profile file is too large' : ($error ?: 'Profile download failed')];
    }
    return [
        'ok' => true,
        'status' => $status,
        'body' => $body,
        'content_type' => (string) ($headers['content-type'] ?? ''),
        'content_disposition' => (string) ($headers['content-disposition'] ?? ''),
        'url' => $finalUrl ?: $url,
    ];
}

function rebeccaSubscriptionArtifacts($panel, array $user, $fetchSubscription = true, $subscriptionUserAgent = 'MirzaBot-Rebecca/1.0')
{
    $artifacts = ['links' => [], 'files' => []];
    $fileHashes = [];
    $panelHost = strtolower((string) (parse_url(rebeccaNormalizeUrl($panel['url_panel'] ?? ''), PHP_URL_HOST) ?: ''));
    $subscriptionUrl = rebeccaAbsoluteUrl($panel, $user['subscription_url'] ?? '');
    $subscriptionHost = strtolower((string) (parse_url($subscriptionUrl, PHP_URL_HOST) ?: ''));
    $allowedHosts = array_values(array_filter(array_unique([$panelHost, $subscriptionHost])));

    $addFile = function ($content, $name = '', $type = '') use (&$artifacts, &$fileHashes) {
        $info = rebeccaProfileInfo($content, $name, $type);
        if (!$info) {
            return false;
        }
        $hash = hash('sha256', (string) $content);
        if (isset($fileHashes[$hash])) {
            return true;
        }
        $fileHashes[$hash] = true;
        $safeName = rebeccaSafeFileName($name);
        $existingExtension = strtolower((string) pathinfo($safeName, PATHINFO_EXTENSION));
        $supportedExtensions = ['conf', 'ovpn', 'mobileconfig', 'zip', 'p12', 'pfx', 'crt', 'cer', 'pem', 'key', 'xml'];
        if (!in_array($existingExtension, $supportedExtensions, true)) {
            $safeName .= '.' . $info['extension'];
        }
        $artifacts['files'][] = [
            'name' => $safeName,
            'mime' => $info['mime'],
            'caption' => $info['caption'],
            'content' => (string) $content,
        ];
        return true;
    };

    $addLink = function ($link) use (&$artifacts) {
        $link = trim((string) $link);
        if ($link !== '' && !in_array($link, $artifacts['links'], true)) {
            $artifacts['links'][] = $link;
        }
    };

    $fileNameFromDownload = function (array $download, $fallback = '') {
        $disposition = (string) ($download['content_disposition'] ?? '');
        if (preg_match('/filename\*=UTF-8\'\'([^;]+)/i', $disposition, $match)) {
            return rawurldecode(trim($match[1], " \t\n\r\0\x0B\"'"));
        }
        if (preg_match('/filename\s*=\s*["\']?([^;"\']+)/i', $disposition, $match)) {
            return trim($match[1]);
        }
        $path = (string) (parse_url($download['url'] ?? '', PHP_URL_PATH) ?: '');
        return basename($path) ?: $fallback;
    };

    $resourceBaseUrl = $subscriptionUrl ?: (rebeccaNormalizeUrl($panel['url_panel'] ?? '') . '/');
    $consumeUrl = function ($url, $name = '') use (&$addFile, &$addLink, $allowedHosts, $fileNameFromDownload, $resourceBaseUrl) {
        $url = rebeccaResolveResourceUrl($resourceBaseUrl, $url);
        if ($url === '') {
            return;
        }
        $path = strtolower((string) (parse_url($url, PHP_URL_PATH) ?: ''));
        $isFileCandidate = preg_match('/\.(conf|ovpn|mobileconfig|zip|p12|pfx|crt|cer|pem|key|xml)$/i', $path)
            || preg_match('/(wireguard|openvpn|amnezia|profile|download)/i', $path);
        if ($isFileCandidate) {
            $download = rebeccaDownloadResource($url, $allowedHosts);
            if (!empty($download['ok'])) {
                $downloadName = $name ?: $fileNameFromDownload($download, 'rebecca-config');
                if ($addFile($download['body'], $downloadName, $download['content_type'])) {
                    return;
                }
            }
        }
        $addLink($url);
    };

    $consume = null;
    $consume = function ($value, $name = '') use (&$consume, &$addFile, &$consumeUrl, &$addLink) {
        if (is_array($value)) {
            $descriptorName = (string) ($value['filename'] ?? $value['file_name'] ?? $value['name'] ?? $name);
            foreach (['content', 'data', 'profile', 'config'] as $contentKey) {
                if (isset($value[$contentKey]) && is_string($value[$contentKey]) && $addFile($value[$contentKey], $descriptorName, $value['mime_type'] ?? $value['content_type'] ?? '')) {
                    return;
                }
            }
            foreach (['download_url', 'file_url', 'url'] as $urlKey) {
                if (!empty($value[$urlKey]) && is_string($value[$urlKey])) {
                    $consumeUrl($value[$urlKey], $descriptorName);
                    return;
                }
            }
            foreach ($value as $child) {
                $consume($child, $descriptorName);
            }
            return;
        }
        if (!is_string($value)) {
            return;
        }
        $value = trim($value);
        if ($value === '' || $addFile($value, $name)) {
            return;
        }
        $decoded = null;
        if (($value[0] === '{' || $value[0] === '[') && is_array($decoded = json_decode($value, true))) {
            $consume($decoded, $name);
            return;
        }
        if (preg_match('#^https?://#i', $value)) {
            $consumeUrl($value, $name);
            return;
        }
        if (preg_match('#^[a-z][a-z0-9+.-]*://#i', $value)) {
            $addLink($value);
            return;
        }
        $compact = preg_replace('/\s+/', '', $value);
        if ($compact !== '' && strlen($compact) % 4 === 0) {
            $decodedBase64 = base64_decode($compact, true);
            if ($decodedBase64 !== false && base64_encode($decodedBase64) === $compact && $addFile($decodedBase64, $name)) {
                return;
            }
        }
        if (strpos($value, "\n") !== false || strpos($value, "\r") !== false) {
            foreach (preg_split('/\r?\n/', $value) as $line) {
                $consume($line, $name);
            }
        }
    };

    foreach (['links', 'files', 'configs', 'profiles', 'subscription_files', 'wireguard_profiles', 'openvpn_profiles'] as $field) {
        if (array_key_exists($field, $user)) {
            $consume($user[$field]);
        }
    }

    if ($fetchSubscription && $subscriptionUrl !== '') {
        $download = rebeccaDownloadResource($subscriptionUrl, $allowedHosts, 8388608, $subscriptionUserAgent);
        if (!empty($download['ok'])) {
            $body = (string) $download['body'];
            $fileName = $fileNameFromDownload($download, 'rebecca-subscription');
            if (!$addFile($body, $fileName, $download['content_type'])) {
                $json = json_decode($body, true);
                if (is_array($json)) {
                    $consume($json);
                } else {
                    $compact = preg_replace('/\s+/', '', $body);
                    $decoded = $compact !== '' ? base64_decode($compact, true) : false;
                    if ($decoded !== false && base64_encode($decoded) === $compact) {
                        $consume($decoded, $fileName);
                    } else {
                        $consume($body, $fileName);
                    }
                }

                if (preg_match_all('/<a\b[^>]*href\s*=\s*["\']([^"\']+)["\'][^>]*>(.*?)<\/a>/is', $body, $matches, PREG_SET_ORDER)) {
                    foreach ($matches as $anchor) {
                        $href = $anchor[1];
                        $anchorText = trim(strip_tags(html_entity_decode($anchor[2], ENT_QUOTES | ENT_HTML5, 'UTF-8')));
                        $resourceUrl = rebeccaResolveResourceUrl($subscriptionUrl, $href);
                        $resourceHint = $resourceUrl . ' ' . $anchorText;
                        if ($resourceUrl !== '' && preg_match('/(wireguard|openvpn|amnezia|profile|download|certificate|\.(conf|ovpn|mobileconfig|zip|p12|pfx|crt|cer|pem|key|xml)(?:\?|$))/i', $resourceHint)) {
                            $consumeUrl($resourceUrl);
                        }
                    }
                }
            }
        }
    }
    return $artifacts;
}

function rebeccaGetSubscriptionLinks($panel, array $user)
{
    $direct = rebeccaSubscriptionArtifacts($panel, $user, false);
    if ($direct['links']) {
        return $direct['links'];
    }
    $complete = rebeccaSubscriptionArtifacts($panel, $user, true);
    return $complete['links'];
}

function rebeccaGetSubscriptionFiles($panel, array $user)
{
    $browserUserAgent = 'Mozilla/5.0 (Linux; Android 13) AppleWebKit/537.36 Chrome/124.0 Mobile Safari/537.36';
    $artifacts = rebeccaSubscriptionArtifacts($panel, $user, true, $browserUserAgent);
    return $artifacts['files'];
}

function rebeccaCreateUser($panel, $product, $username, $expire, $dataLimit, $note, $isTest = false)
{
    $serviceId = rebeccaResolveServiceId($panel, $product);
    if ($serviceId < 1) {
        return ['ok' => false, 'status' => 0, 'msg' => 'ابتدا سرویس پیش‌فرض پنل ربکا را از مدیریت پنل انتخاب کنید.', 'data' => []];
    }
    $resetStrategy = (string) ($product['data_limit_reset'] ?? 'no_reset');
    if (!in_array($resetStrategy, ['no_reset', 'day', 'week', 'month', 'year'], true)) {
        $resetStrategy = 'no_reset';
    }
    $payload = [
        'username' => (string) $username,
        'service_id' => $serviceId,
        'status' => 'active',
        'expire' => (int) $expire > 0 ? (int) $expire : null,
        'data_limit' => max(0, (int) $dataLimit),
        'data_limit_reset_strategy' => $resetStrategy,
        'note' => (string) $note,
    ];
    $useOnHold = $isTest
        ? (($panel['on_hold_test'] ?? '1') !== '0')
        : (($panel['conecton'] ?? 'offconecton') !== 'offconecton');
    if ($useOnHold && (int) $expire > time()) {
        $payload['status'] = 'on_hold';
        $payload['expire'] = null;
        $payload['on_hold_expire_duration'] = (int) $expire - time();
    }
    $response = rebeccaRequest($panel, 'post', '/api/user', $payload);
    if ($response['ok'] && empty($response['data']['subscription_url']) && empty($response['data']['links'])) {
        $fullUser = rebeccaGetUser($panel, $username);
        if ($fullUser['ok']) {
            $response['data'] = $fullUser['data'];
        }
    }
    return $response;
}

function rebeccaGetUser($panelOrName, $username)
{
    return rebeccaRequest($panelOrName, 'get', '/api/user/' . rawurlencode((string) $username));
}

function rebeccaModifyUser($panelOrName, $username, array $payload)
{
    $allowed = [
        'status', 'service_id', 'expire', 'data_limit', 'data_limit_reset_strategy',
        'note', 'telegram_id', 'contact_number', 'on_hold_expire_duration',
        'on_hold_timeout', 'ip_limit', 'auto_delete_in_days', 'flow', 'credential_key',
    ];
    $payload = array_intersect_key($payload, array_flip($allowed));
    if (!$payload) {
        return ['ok' => false, 'status' => 0, 'msg' => 'اطلاعاتی برای ویرایش کاربر ارسال نشده است.', 'data' => []];
    }
    return rebeccaRequest($panelOrName, 'put', '/api/user/' . rawurlencode((string) $username), $payload);
}

function rebeccaDeleteUser($panelOrName, $username)
{
    return rebeccaRequest($panelOrName, 'delete', '/api/user/' . rawurlencode((string) $username));
}

function rebeccaResetUserUsage($panelOrName, $username)
{
    return rebeccaRequest($panelOrName, 'post', '/api/user/' . rawurlencode((string) $username) . '/reset', []);
}

function rebeccaRevokeSubscription($panelOrName, $username)
{
    return rebeccaRequest($panelOrName, 'post', '/api/user/' . rawurlencode((string) $username) . '/revoke_sub', []);
}

function rebeccaUserOutput($panel, array $user, $customSubscriptionUrl = null)
{
    $subscriptionUrl = rebeccaAbsoluteUrl($panel, $user['subscription_url'] ?? '');
    return [
        'status' => (string) ($user['status'] ?? 'active'),
        'username' => (string) ($user['username'] ?? ''),
        'data_limit' => (int) ($user['data_limit'] ?? 0),
        'expire' => isset($user['expire']) ? (int) $user['expire'] : 0,
        'online_at' => $user['online_at'] ?? null,
        'used_traffic' => (int) ($user['used_traffic'] ?? 0),
        'links' => rebeccaGetSubscriptionLinks($panel, $user),
        'subscription_url' => $customSubscriptionUrl ?: $subscriptionUrl,
        'panel_subscription_url' => $subscriptionUrl,
        'sub_updated_at' => $user['sub_updated_at'] ?? null,
        'sub_last_user_agent' => $user['sub_last_user_agent'] ?? null,
        'uuid' => $user['proxies'] ?? $user['credential_key'] ?? null,
        'data_limit_reset' => $user['data_limit_reset_strategy'] ?? 'no_reset',
        'service_id' => isset($user['service_id']) ? (int) $user['service_id'] : null,
        'service_name' => $user['service_name'] ?? null,
    ];
}

function rebeccaServicesKeyboardData($panel, $selectedServiceId, $callbackPrefix, $title)
{
    $services = rebeccaGetServices($panel);
    if (!$services['ok']) {
        return ['ok' => false, 'msg' => $services['msg'], 'text' => '', 'keyboard' => null];
    }
    if (!$services['items']) {
        return ['ok' => false, 'msg' => 'هیچ سرویسی در پنل ربکا ساخته نشده است.', 'text' => '', 'keyboard' => null];
    }
    $selectedServiceId = (int) $selectedServiceId;
    $rows = [];
    foreach ($services['items'] as $service) {
        $id = (int) $service['id'];
        $name = trim((string) ($service['name'] ?? ('Service ' . $id)));
        if (function_exists('mb_strlen') && mb_strlen($name, 'UTF-8') > 48) {
            $name = mb_substr($name, 0, 45, 'UTF-8') . '...';
        }
        $rows[] = [[
            'text' => ($id === $selectedServiceId ? '✅ ' : '') . $name,
            'callback_data' => $callbackPrefix . $id,
        ]];
    }
    $rows[] = [[
        'text' => 'بازگشت به مدیریت',
        'callback_data' => 'admin',
    ]];
    return [
        'ok' => true,
        'msg' => '',
        'text' => "🧩 <b>{$title}</b>\n\nهر سرویس تمام پروتکل‌های فعال روی میزبان‌های خودش را به کاربر تحویل می‌دهد. سرویس موردنظر را انتخاب کنید:",
        'keyboard' => json_encode(['inline_keyboard' => $rows], JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES),
    ];
}

function rebeccaServiceProtocols($panel, $serviceId)
{
    if ((int) $serviceId < 1) {
        return [];
    }
    $response = rebeccaGetService($panel, $serviceId);
    if (!$response['ok']) {
        return [];
    }
    $protocols = [];
    foreach (($response['data']['hosts'] ?? []) as $host) {
        $protocol = strtolower(trim((string) ($host['inbound_protocol'] ?? '')));
        if ($protocol !== '') {
            $protocols[] = $protocol;
        }
    }
    return array_values(array_unique($protocols));
}

